In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv(r"C:\Users\user\Downloads\insurance.csv")

In [3]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [5]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
x=data.iloc[:,0:6]

In [7]:
y=data.iloc[:,6]

In [8]:
x.head()

age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [9]:
x=data.iloc[:,0:6].values
y=data.iloc[:,6].values

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")

In [12]:
x=ct.fit_transform(x)

In [13]:
x.shape

(1338, 11)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [20]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [21]:
ann.compile("adam","mse",metrics=["mse"])

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
1070/1070 [==============================] - 4s 3ms/sample - loss: 317636752.3888 - mean_squared_error: 317636736.0000
Epoch 2/1000
1070/1070 [==============================] - 1s 602us/sample - loss: 317634453.1738 - mean_squared_error: 317634432.0000
Epoch 3/1000
1070/1070 [==============================] - 0s 241us/sample - loss: 317628519.1776 - mean_squared_error: 317628480.0000
Epoch 4/1000
1070/1070 [==============================] - 0s 234us/sample - loss: 317614466.3925 - mean_squared_error: 317614528.0000
Epoch 5/1000
1070/1070 [==============================] - 0s 219us/sample - loss: 317584797.9664 - mean_squared_error: 317584800.0000
Epoch 6/1000
1070/1070 [==============================] - 0s 382us/sample - loss: 317535037.7271 - mean_squared_error: 317535104.0000
Epoch 7/1000
1070/1070 [==============================] - 0s 340us/sample - loss: 317457550.3850 - mean_squared_error: 317457600.0000
Epoch 8/1000
1070/1070 [==============================] - 0s 322

In [23]:
ypred=ann.predict(x_test)

In [24]:
ypred

array([[ 9977.306 ],
       [10097.429 ],
       [47269.188 ],
       [16030.323 ],
       [11993.056 ],
       [ 7091.1846],
       [ 3772.7173],
       [14261.073 ],
       [ 9361.571 ],
       [ 7113.3403],
       [10814.079 ],
       [11435.14  ],
       [ 9177.676 ],
       [ 5809.6763],
       [26414.77  ],
       [12460.96  ],
       [12573.146 ],
       [ 3842.763 ],
       [ 7844.21  ],
       [27300.125 ],
       [28827.459 ],
       [14341.509 ],
       [11573.941 ],
       [30340.29  ],
       [ 2234.1975],
       [ 6556.069 ],
       [ 8499.503 ],
       [ 9525.669 ],
       [ 5101.5215],
       [ 9605.983 ],
       [ 9873.672 ],
       [49866.59  ],
       [13722.326 ],
       [11081.397 ],
       [16191.386 ],
       [ 6525.924 ],
       [10364.824 ],
       [36585.02  ],
       [35748.973 ],
       [ 3830.9038],
       [ 8721.7295],
       [ 3604.6885],
       [27322.822 ],
       [45619.28  ],
       [33354.41  ],
       [ 4473.23  ],
       [12431.991 ],
       [ 7952

In [25]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [26]:
yy=ann.predict(sc.transform(ct.transform([[19,"female",27.900,0,"yes","southwest"]])))

In [27]:
yy

array([[23764.678]], dtype=float32)

In [28]:
ann.predict(sc.transform(ct.transform([[18,"male",33.770,0,"no","southwest"]])))

array([[2946.9878]], dtype=float32)

In [29]:
ann.predict(sc.transform(ct.transform([[28,"male",33.00,3,"no","southwest"]])))

array([[3256.3906]], dtype=float32)