In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\user\Downloads\Bank_Personal_Loan_Modelling.csv")

In [3]:
data.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
data.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [6]:
data.drop(columns=["ID","ZIP Code"],inplace=True)

In [7]:
data.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [8]:
x=data.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=data.iloc[:,7].values

In [9]:
x

array([[25.,  1., 49., ...,  0.,  0.,  0.],
       [45., 19., 34., ...,  0.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  1.,  0.],
       [28.,  4., 83., ...,  0.,  1.,  1.]])

In [10]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
x_train.shape

(4000, 11)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
ann=Sequential()

In [16]:
ann.add(Dense(11,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
ann.add(Dense(22,kernel_initializer="random_uniform",activation="relu"))

In [18]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [19]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/50
4000/4000 [==============================] - 7s 2ms/sample - loss: 0.4998 - acc: 0.9018
Epoch 2/50
4000/4000 [==============================] - 2s 418us/sample - loss: 0.1981 - acc: 0.9025
Epoch 3/50
4000/4000 [==============================] - 2s 457us/sample - loss: 0.1632 - acc: 0.9025
Epoch 4/50
4000/4000 [==============================] - 1s 311us/sample - loss: 0.1356 - acc: 0.9258
Epoch 5/50
4000/4000 [==============================] - 2s 434us/sample - loss: 0.1120 - acc: 0.9613s - lo
Epoch 6/50
4000/4000 [==============================] - 1s 306us/sample - loss: 0.0970 - acc: 0.9690
Epoch 7/50
4000/4000 [==============================] - 1s 291us/sample - loss: 0.0876 - acc: 0.9730
Epoch 8/50
4000/4000 [==============================] - 1s 285us/sample - loss: 0.0812 - acc: 0.9745
Epoch 9/50
4000/4000 [==============================] - 1s 296us/sample - loss: 0.0755 - acc: 

In [21]:
ypred=ann.predict(x_test)

In [22]:
ypred

array([[0.00000000e+00],
       [1.19209290e-06],
       [1.31458044e-04],
       [4.59402800e-04],
       [1.74010396e-02],
       [5.18560410e-06],
       [9.31683064e-01],
       [9.95803833e-01],
       [2.64831483e-02],
       [1.49011612e-07],
       [4.47034836e-07],
       [4.14198637e-03],
       [4.76837158e-07],
       [5.56716323e-03],
       [6.08085990e-02],
       [1.26268864e-02],
       [1.19209290e-07],
       [1.88529491e-04],
       [1.49011612e-07],
       [2.63035297e-04],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.53125525e-02],
       [9.96593118e-01],
       [3.87430191e-07],
       [1.51395798e-05],
       [9.96593118e-01],
       [9.08316016e-01],
       [0.00000000e+00],
       [3.12924385e-05],
       [8.96751881e-05],
       [3.01003456e-06],
       [1.89304352e-03],
       [2.33054161e-05],
       [1.63495541e-04],
       [1.23977661e-05],
       [2.04890966e-04],
       [1.13093853e-03],
       [1.04799867e-03],
       [4.71282005e-03],


In [23]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [24]:
yy=ann.predict(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))


In [25]:
yy

array([[9.353208e-08]], dtype=float32)

In [26]:
yp=ann.predict(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))

In [27]:
yp>0.5

array([[False]])

In [28]:
yp=ann.predict(sc.transform([[54,0,73,7,3.2,0,0,1,1,1,1]]))
yp>0.5

array([[False]])

In [29]:
yp=ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))
yp>0.5

array([[ True]])