In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv(r"C:\Users\user\Downloads\Categorical.csv")

In [3]:
data.head()

name  Longitude   Latitude      continent
0        Aruba -69.982677  12.520880  North America
1  Afghanistan  66.004734  33.835231           Asia
2       Angola  17.537368 -12.293361         Africa
3     Anguilla -63.064989  18.223959  North America
4      Albania  20.049834  41.142450         Europe

In [4]:
data.isnull().sum()

name         0
Longitude    0
Latitude     0
continent    0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 4 columns):
name         241 non-null object
Longitude    241 non-null float64
Latitude     241 non-null float64
continent    241 non-null object
dtypes: float64(2), object(2)
memory usage: 7.6+ KB


In [6]:
data["name"].unique()

array(['Aruba', 'Afghanistan', 'Angola', 'Anguilla', 'Albania', 'Aland',
       'Andorra', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antarctica', 'Ashmore and Cartier Is.',
       'Fr. S. Antarctic Lands', 'Antigua and Barb.', 'Australia',
       'Austria', 'Azerbaijan', 'Burundi', 'Belgium', 'Benin',
       'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Canada',
       'Bahamas', 'Bosnia and Herz.', 'St-Barthélemy', 'Belarus',
       'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados', 'Brunei',
       'Bhutan', 'Botswana', 'Central African Rep.', 'Switzerland',
       'Chile', 'China', "Côte d'Ivoire", 'Cameroon', 'Dem. Rep. Congo',
       'Congo', 'Cook Is.', 'Colombia', 'Comoros', 'Cape Verde',
       'Costa Rica', 'Cuba', 'Curaçao', 'Cayman Is.', 'N. Cyprus',
       'Cyprus', 'Czech Rep.', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Rep.', 'Algeria', 'Ecuador', 'Egypt',
       'Eritrea', 'Spain', 'Estonia', 'Ethiopia',

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["name"]=le.fit_transform(data["name"])

In [8]:
x=data.iloc[:,0:3]
y=data.iloc[:,3]

In [9]:
x.head()

name  Longitude   Latitude
0    12 -69.982677  12.520880
1     0  66.004734  33.835231
2     6  17.537368 -12.293361
3     7 -63.064989  18.223959
4     2  20.049834  41.142450

In [10]:
y.head()

0    North America
1             Asia
2           Africa
3    North America
4           Europe
Name: continent, dtype: object

In [11]:
x=data.iloc[:,0:3].values
y=data.iloc[:,3:4].values

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [14]:
y

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [15]:
y.shape

(241, 8)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
cat=Sequential()

In [20]:
cat.add(Dense(3,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
cat.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

In [22]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="softmax"))

In [23]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [24]:
cat.fit(x_train,y_train,batch_size=32,epochs=1500)

Epoch 1/1500
192/192 [==============================] - 3s 16ms/sample - loss: 2.0781 - acc: 0.2135
Epoch 2/1500
192/192 [==============================] - 0s 784us/sample - loss: 2.0747 - acc: 0.2083
Epoch 3/1500
192/192 [==============================] - 0s 600us/sample - loss: 2.0714 - acc: 0.2083
Epoch 4/1500
192/192 [==============================] - 0s 336us/sample - loss: 2.0681 - acc: 0.3542
Epoch 5/1500
192/192 [==============================] - 0s 504us/sample - loss: 2.0648 - acc: 0.3958
Epoch 6/1500
192/192 [==============================] - 0s 511us/sample - loss: 2.0612 - acc: 0.3229
Epoch 7/1500
192/192 [==============================] - 0s 550us/sample - loss: 2.0574 - acc: 0.2292
Epoch 8/1500
192/192 [==============================] - 1s 5ms/sample - loss: 2.0533 - acc: 0.2188
Epoch 9/1500
192/192 [==============================] - 1s 3ms/sample - loss: 2.0487 - acc: 0.2188
Epoch 10/1500
192/192 [==============================] - 0s 1ms/sample - loss: 2.0440 - acc: 0.2

In [25]:
ypred=cat.predict(x_test)

In [26]:
ypred

array([[1.55659601e-01, 2.60849924e-06, 3.61206442e-01, 4.83131260e-01,
        2.22521965e-08, 1.04474513e-12, 1.69432024e-09, 1.55750137e-18],
       [7.98657254e-07, 5.40512701e-06, 0.00000000e+00, 1.24415000e-20,
        2.13532203e-07, 1.76293347e-02, 2.66803941e-03, 9.79696155e-01],
       [8.78529131e-01, 2.65064575e-02, 4.33841443e-08, 3.96697653e-09,
        6.39453379e-10, 1.97192669e-04, 9.47672203e-02, 4.48990534e-08],
       [2.17397421e-04, 6.24516222e-04, 1.08971067e-01, 4.76359247e-07,
        6.54200513e-11, 8.68082166e-01, 2.21043397e-02, 3.97761646e-08],
       [1.83191535e-03, 1.48929233e-08, 1.78757691e-27, 9.87282515e-01,
        1.08856047e-02, 1.99420775e-13, 1.39605363e-12, 4.18600010e-17],
       [1.83560885e-02, 4.42782266e-07, 1.93144812e-19, 9.80920434e-01,
        7.23032514e-04, 9.59302082e-12, 1.64783617e-10, 4.86601423e-16],
       [9.98287857e-01, 1.08311092e-03, 1.32841079e-17, 4.85313416e-04,
        9.99570912e-05, 1.35045775e-06, 4.23352758e-05, 4.

In [27]:
y_test

array([[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [0.0, 0.0, 0.

In [28]:
data.head()

name  Longitude   Latitude      continent
0    12 -69.982677  12.520880  North America
1     0  66.004734  33.835231           Asia
2     6  17.537368 -12.293361         Africa
3     7 -63.064989  18.223959  North America
4     2  20.049834  41.142450         Europe

In [29]:

cat.predict_classes(sc.transform([[12,-69.982677,12.52088]]))

array([4], dtype=int64)

In [30]:

cat.predict(sc.transform([[12,-69.982677,12.52088]]))

array([[4.8618682e-07, 5.3520985e-08, 0.0000000e+00, 3.7551955e-14,
        9.9765164e-01, 2.8834640e-05, 8.3512411e-08, 2.3188926e-03]],
      dtype=float32)

In [31]:

cat.predict_classes(sc.transform([[0,66.004734,33.835231]]))

array([2], dtype=int64)

In [32]:

cat.predict_classes(sc.transform([[0,66.004734,33.835231]]))

array([2], dtype=int64)