In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\user\Downloads\healthcare-dataset-stroke-data.csv")

In [3]:
data.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
data.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:
data["bmi"].fillna(data["bmi"].mean(),inplace=True)

In [6]:
data.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
id                   5110 non-null int64
gender               5110 non-null object
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
ever_married         5110 non-null object
work_type            5110 non-null object
Residence_type       5110 non-null object
avg_glucose_level    5110 non-null float64
bmi                  5110 non-null float64
smoking_status       5110 non-null object
stroke               5110 non-null int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.1+ KB


In [8]:
x=data.iloc[:,1:11]
y=data.iloc[:,11]

In [9]:
x.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level        bmi   smoking_status  
0          Urban             228.69  36.600000  formerly smoked  
1          Rural             202.21  28.893237     never smoked  
2          Rural             105.92  32.500000     never smoked  
3          Urban             171.23  34.400000           smokes  
4          Rural             174.12  24.000000     never smoked

In [10]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: stroke, dtype: int64

In [11]:
x=data.iloc[:,1:11].values
y=data.iloc[:,11].values

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
ct=ColumnTransformer([("oh",OneHotEncoder(),[0,4,5,6,9])],remainder="passthrough")

In [14]:
x=ct.fit_transform(x)

In [15]:
x.shape

(5110, 21)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)


In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
ann=Sequential()

In [20]:
ann.add(Dense(10,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
ann.add(Dense(20,kernel_initializer="random_uniform",activation="relu"))

In [22]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [23]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [24]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/50
4088/4088 [==============================] - 8s 2ms/sample - loss: 0.5150 - acc: 0.9469
Epoch 2/50
4088/4088 [==============================] - 1s 344us/sample - loss: 0.1808 - acc: 0.9523
Epoch 3/50
4088/4088 [==============================] - 1s 363us/sample - loss: 0.1636 - acc: 0.9523
Epoch 4/50
4088/4088 [==============================] - 2s 469us/sample - loss: 0.1595 - acc: 0.9523
Epoch 5/50
4088/4088 [==============================] - 2s 582us/sample - loss: 0.1567 - acc: 0.9523
Epoch 6/50
4088/4088 [==============================] - 3s 668us/sample - loss: 0.1548 - acc: 0.9523s - lo - ETA: 0s - loss: 0.1558 - acc: 0.951
Epoch 7/50
4088/4088 [==============================] - 3s 651us/sample - loss: 0.1531 - acc: 0.9523
Epoch 8/50
4088/4088 [==============================] - 3s 775us/sample - loss: 0.1520 - acc: 0.9523
Epoch 9/50
4088/4088 [==============================] - 

In [25]:
ypred=ann.predict(x_test)

In [26]:
ypred

array([[4.2619234e-01],
       [1.1920929e-07],
       [2.4664342e-02],
       ...,
       [1.0312527e-02],
       [1.8730873e-01],
       [8.7382030e-03]], dtype=float32)

In [27]:
y_test

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [28]:
yy=ann.predict(sc.transform(ct.transform([["Male",67.0,0,1,"Yes","Private","Urban",228.69,36.6,"formerly smoked"]])))

yy

array([[0.22756775]], dtype=float32)

In [31]:
yy=ann.predict(sc.transform(ct.transform([["Male",55,0,0,"Yes","Private","Urban",72.03,37,"smokes"]])))
yy>0.5

array([[False]])

In [32]:
yy=ann.predict(sc.transform(ct.transform([["Female",63,0,0,"Yes","Self-employed","Rural",75.93,34.7,"formerly smoked"]])))
yy>0.5

array([[False]])