In [1]:
import numpy as np
import pandas as pd



In [2]:
data=pd.read_csv(r"C:\Users\user\Downloads\Prostate_Cancer.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
id                   100 non-null int64
diagnosis_result     100 non-null object
radius               100 non-null int64
texture              100 non-null int64
perimeter            100 non-null int64
area                 100 non-null int64
smoothness           100 non-null float64
compactness          100 non-null float64
symmetry             100 non-null float64
fractal_dimension    100 non-null float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [4]:
data.isnull().sum()

id                   0
diagnosis_result     0
radius               0
texture              0
perimeter            0
area                 0
smoothness           0
compactness          0
symmetry             0
fractal_dimension    0
dtype: int64

In [5]:
data["diagnosis_result"].unique()

array(['M', 'B'], dtype=object)

In [6]:
x=data.iloc[:,2:10]
y=data.iloc[:,1:2]

In [7]:
data.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [8]:
y.head()

diagnosis_result
0                M
1                B
2                M
3                M
4                M

In [9]:
x=data.iloc[:,2:10].values
y=data.iloc[:,1:2].values

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [12]:
y

array([[0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0,

In [13]:
y.shape

(100, 2)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
cat=Sequential()

In [19]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [20]:
cat.add(Dense(16,kernel_initializer="random_uniform",activation="relu"))

In [21]:
cat.add(Dense(2,kernel_initializer="random_uniform",activation="softmax"))

In [22]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [23]:
cat.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
80/80 [==============================] - 3s 36ms/sample - loss: 0.6933 - acc: 0.4625
Epoch 2/20
80/80 [==============================] - 0s 2ms/sample - loss: 0.6930 - acc: 0.6625
Epoch 3/20
80/80 [==============================] - 1s 7ms/sample - loss: 0.6927 - acc: 0.5625
Epoch 4/20
80/80 [==============================] - 0s 4ms/sample - loss: 0.6924 - acc: 0.5625
Epoch 5/20
80/80 [==============================] - 0s 567us/sample - loss: 0.6920 - acc: 0.5625
Epoch 6/20
80/80 [==============================] - 0s 750us/sample - loss: 0.6916 - acc: 0.5625
Epoch 7/20
80/80 [==============================] - 1s 6ms/sample - loss: 0.6910 - acc: 0.5625
Epoch 8/20
80/80 [==============================] - 0s 4ms/sample - loss: 0.6904 - acc: 0.5625
Epoch 9/20
80/80 [==============================] - 0s 499us/sample - loss: 0.6896 - acc: 0.5625
Epoch 10/20
80/80 [==============================] - 0s 784us/sample - loss: 0.6886 - acc: 0.5625
Epoch 11/20
80/80 [=====================

In [24]:
ypred=cat.predict(x_test)

In [25]:
ypred

array([[0.477278  , 0.52272207],
       [0.50179344, 0.49820662],
       [0.45340058, 0.54659945],
       [0.51298237, 0.48701763],
       [0.5010018 , 0.49899825],
       [0.4999158 , 0.50008416],
       [0.49090445, 0.50909555],
       [0.5046604 , 0.49533957],
       [0.5050249 , 0.49497512],
       [0.44910243, 0.55089754],
       [0.45767257, 0.54232734],
       [0.5120304 , 0.4879696 ],
       [0.42209056, 0.5779094 ],
       [0.48266625, 0.51733375],
       [0.484357  , 0.51564306],
       [0.44440162, 0.5555983 ],
       [0.47682956, 0.52317053],
       [0.4517487 , 0.5482512 ],
       [0.44244412, 0.5575558 ],
       [0.4839578 , 0.51604223]], dtype=float32)

In [26]:
y_test

array([[0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0]], dtype=object)

In [27]:

cat.predict_classes(sc.transform([[23,12,151,954,0.143,0.278,0.242,0.079]]))

array([1], dtype=int64)

In [28]:
cat.predict_classes(sc.transform([[9,9,183,2326,0.343,0.062,0.191,0.027]]))

array([1], dtype=int64)

In [29]:
cat.predict_classes(sc.transform([[25,25,83,477,0.128,0.170,0.209,0.076]]))

array([1], dtype=int64)

In [30]:
yp=cat.predict(sc.transform([[25,25,83,477,0.128,0.170,0.209,0.076]]))

In [31]:
yp>0.5

array([[False,  True]])

In [32]:
yp

array([[0.4961476, 0.5038524]], dtype=float32)