In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\user\Downloads\Real estate.csv")

In [3]:
data.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
No                                        414 non-null int64
X1 transaction date                       414 non-null float64
X2 house age                              414 non-null float64
X3 distance to the nearest MRT station    414 non-null float64
X4 number of convenience stores           414 non-null int64
X5 latitude                               414 non-null float64
X6 longitude                              414 non-null float64
Y house price of unit area                414 non-null float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [5]:
data.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [6]:
x=data.iloc[:,1:7]
y=data.iloc[:,7]

In [7]:
x.head()

X1 transaction date  X2 house age  X3 distance to the nearest MRT station  \
0             2012.917          32.0                                84.87882   
1             2012.917          19.5                               306.59470   
2             2013.583          13.3                               561.98450   
3             2013.500          13.3                               561.98450   
4             2012.833           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  
0                               10     24.98298     121.54024  
1                                9     24.98034     121.53951  
2                                5     24.98746     121.54391  
3                                5     24.98746     121.54391  
4                                5     24.97937     121.54245

In [8]:
y.head()

0    37.9
1    42.2
2    47.3
3    54.8
4    43.1
Name: Y house price of unit area, dtype: float64

In [9]:
x=data.iloc[:,1:7].values
y=data.iloc[:,7].values

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [13]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
ann=Sequential()

In [16]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [18]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [19]:
ann.compile("adam","mse",metrics=["mse"])

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
331/331 [==============================] - 3s 8ms/sample - loss: 1629.2388 - mean_squared_error: 1629.2389
Epoch 2/1000
331/331 [==============================] - 1s 4ms/sample - loss: 1628.0959 - mean_squared_error: 1628.0959
Epoch 3/1000
331/331 [==============================] - 2s 5ms/sample - loss: 1626.6246 - mean_squared_error: 1626.6246
Epoch 4/1000
331/331 [==============================] - 1s 4ms/sample - loss: 1624.6648 - mean_squared_error: 1624.6650
Epoch 5/1000
331/331 [==============================] - 1s 3ms/sample - loss: 1621.8880 - mean_squared_error: 1621.8882
Epoch 6/1000
331/331 [==============================] - 1s 3ms/sample - loss: 1618.0141 - mean_squared_error: 1618.0139
Epoch 7/1000
331/331 [==============================] - 1s 4ms/sample - loss: 1612.6735 - mean_squared_error: 1612.6733
Epoch 8/1000
331/331 [==============================] - 2s 5ms/sample - loss: 1605.1636 - mean_squared_error: 1605.1636
Epoch 9/1000
331/331 [==================

In [21]:
ypred=ann.predict(x_test)

In [22]:
ypred

array([[43.36544 ],
       [20.212124],
       [42.901936],
       [20.21934 ],
       [49.011234],
       [36.879993],
       [40.434864],
       [38.0117  ],
       [49.42136 ],
       [46.474064],
       [43.831882],
       [35.26117 ],
       [43.185158],
       [37.8678  ],
       [50.351067],
       [40.315144],
       [35.064625],
       [46.815952],
       [36.033295],
       [40.678738],
       [52.413387],
       [25.715778],
       [34.41361 ],
       [46.589214],
       [49.37893 ],
       [40.760357],
       [41.323063],
       [21.570072],
       [49.22139 ],
       [18.682825],
       [43.657154],
       [33.852352],
       [46.28551 ],
       [43.916115],
       [39.74546 ],
       [25.920013],
       [45.62448 ],
       [33.64211 ],
       [50.774754],
       [20.134226],
       [53.848354],
       [34.502674],
       [27.222046],
       [48.96371 ],
       [19.648176],
       [39.89496 ],
       [36.00907 ],
       [17.619535],
       [30.6156  ],
       [48.232872],


In [23]:
y_test

array([45.3, 14.4, 46. , 15.6, 50.2, 38.1, 48.5, 41.4, 51.6, 40.1, 42. ,
       42.4, 28.5, 39.1, 53.7, 36.8, 40.6, 55.2, 39.3, 44.3, 53.5, 25.3,
       22.8, 51.7, 45.5, 34.4, 31.6, 25.9, 49.5, 24.7, 51.7, 29.7, 45.4,
       50.5, 26.5, 30.1, 46.1, 28.9, 54.4, 15. , 44.9, 29.8, 23.6, 48. ,
       16.7, 40.9, 40.2, 12.9, 21.3, 62.1, 63.9, 40.3, 42.2, 19.1, 28.4,
       28.5, 60.7, 37.5, 39.3, 28.8, 42.3, 44.3, 42.6, 57.4, 42.2, 25.7,
       13.2, 27. , 56.2, 38.3, 20.8, 43.1, 78.3, 20.9, 32.5, 33.4, 32.1,
       19.2, 53. , 38.2, 46.7, 24.6, 36.2])

In [24]:
data.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [25]:
yy=ann.predict(sc.transform([[2012.917,32.0,84.87882,10,24.98298,121.54024]]))

In [26]:
yy

array([[44.741802]], dtype=float32)

In [27]:
ann.predict(sc.transform([[2012.917,19.5,306.5947,9,24.98034,121.53951]]))

array([[43.055134]], dtype=float32)

In [28]:
ann.predict(sc.transform([[2013.500,13.3,561.98450,5,24.98746,121.54391]]))

array([[48.952103]], dtype=float32)